### PR TITLE
 Bubble sort for Numbers and String

### PR DESCRIPTION
**Pull request by bmuhamood**
Milestone one

- Built a method #bubble_sort that takes an array and returns a sorted array.
- The bubble_sort sorts both Numerical Values and String Values from smallest to largest.
- Linters working fine
- I'm unable to resolve the below linter errors - Kindly request to advise.
- Resolved Branch issues to GitHub flow

### CODE REVIEW

**Review by adaorachi — COMMENTED** [review]
### Hi @bmuhamood, :wave: 

Well done on the completion of this project but sadly I cannot review it because it did not follow the correct Github flow structure. You are supposed to use the `Github-flow` structure and not `Gitflow` structure, which means to make a pull request from a feature branch to the master branch and not to the development branch.  You are only allowed to use Gitflow starting from the `enumerables` project. Here is [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/git.png) from the project requirement in [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/).

Kindly fix the issue stated above and request for another code review once you are ready.

I am sorry to inform you that this Code Review Request will be marked as invalid in your dashboard.
- [ ] Possible ways to fix this is to create a brand new repo with the correct setup and feature branch (with DESCRIPTIVE name) and copy your code there OR close this pull request and create another one with the correct feature branch and structure.

---

### STATUS: INVALID

---

Should you have any questions, kindly reach out to me on Slack with the username @adaorachi.

Happy Coding :relaxed: 

MaryAnn Chukwuka.

**Comment by bmuhamood** [comment]
Milestone 2

Thanks a lot for the review and feedback. 

- Followed the **Github flow**. 
- Created **feature-branch** and develop branch. 
- Worked on feature-branch and left **develop** branch empty. 
- Branch can be merged from **feature-branch** to develop branch once approved.

**Review by trekab — COMMENTED** [review]
## Invalid: :stop_sign: 
Hi @bmuhamood! You have done well following `GitFlow` for this project but I don't see any `README.md` file for your `feature-branch`. This makes your repository unprofessional. Please check out this [professional repository guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) from pathwright and make the necessary changes before you submit another code review request.

_Feel free to reach me on slack for any inquiries about this feedback._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by bmuhamood** [comment]
Milestone 4

- Readme file added to make the project look professional.

**Review by trekab — CHANGES_REQUESTED** [review]
## Changes Required! :recycle: 
Hi @bmuhamood! Well done on this project so far. There are some changes I'd like you to make before we can have this project approved. These include:
- [ ] Please setup linting for your project. Use config files copied from [config linter repository](https://github.com/microverseinc/linters-config#linters-config)
- [ ] The `bubble_sort_by` method should raise a `LocalJumpError` if a block is not given
- [ ] __[OPTIONAL]__ I see that you gave your methods the same name. Please rename the second method more appropriately (`bubble_sort_by`) since this name would be more descriptive of what the method does.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by bmuhamood** [comment]
Milestone 5

- Fixed all of the above issues and added linters in the project.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @bmuhamood  👋

⭕ INVALID

This pull request has been marked as invalid.

Reason:
- As stated in the first review you are expected to follow the GitHub flow guide.

**To do:**
 - Please close this pull request and open a new one from **feature-branch to master branch**.

**Comment by bmuhamood** [comment]
Milstone 6

Following GITHUB flow, Once the project is approved, i merge from feature branch to develop branch, Now in the above review, i have to create 2 branch, Feature branch and Master only. Im so confused now. 

I have already resolved these issues in the first, second and third code reviews and below was the advise from the first code review. Now i'm confused. I must have three branch i.e. develop, feature and Master. 

"What I do is just the following:
Creating a repo
5:38
2. Create a development or dev branch
5:38
3. Push the empty branch and cd in it
5:39
4. Create a feature branch feature/bubble-sort
5:39
5. Push the branch and cd in it
5:39
6. Work on my feature branch until I've finished
5:39
7. Create a PR from that feature branch to merge into development or dev
5:39
8. Ask for a code review
5:40
9. When approved, you can merge from feature to development or dev (edited) 
5:40
10. Then merge from development or dev to master
5:40
And that's it!
5:40
The reason for this is that it mimics the workflow of a real project in a real company
5:40
they don't touch master until they are absolutely sure everything works
5:40
otherwise the app would crash
5:41
Since you didn't do this, you will have to push commit by commit in the new branch
5:42
until you have everything you need to
5:42
then restore dev to the original commit so that you can compare it and merge
5:42
you can also create a new branch development from master, it will be empty and that works
5:43
then open the PR from the feature branch you created and that has all the commits you pushed again
5:43
open the PR from there to development (the one that is empty)
5:43
delete all the branches you don't need
5:43
but remember to save your code so you don't lose it"

**Review by expjazz — CHANGES_REQUESTED** [review]
##Status: Changes Required :recycle:  

Hello :+1: 

You did a good job here :clap: 

However, there is still one detail that was previously asked that you have not yet implemented:

image

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Review by kubilaycaglayan — APPROVED** [review]
Hello Team 👋 
Status: Project Approved 🟢 

Thanks for your efforts and time 🙏 

With all my respect...

**Comment by bmuhamood** [comment]
Appreciated a lot all for your kind support and advise.

**Pull request merged**
